MA-5899 fix sabreauto_6q lollipop nand compile error
be lack of cryptfs.h when compile lollipop nand on sabreauto_6q
fatal error: cryptfs.h: No such file or directory

Signed-off-by: zhang sanshan <b51434@freescale.com>

Conflicts:
	Android.mk